### PR TITLE
pin Docker version (18.09.7)

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Updating docker to 19.03 was assumed to fix overlay issue #7, but no success :(

**Comment by weber-software** [comment]
The pinning is great! But since the 19.03-rc isn't fixing #7 i think we should wait for the final 19.03.

**Comment by AkihiroSuda** [comment]
#16 should fix the overlay issue

**Comment by AkihiroSuda** [comment]
modified the PR to pin 18.09

**Pull request merged**
